### ISSUE TITLE
What happens after export?

### ISSUE THREAD

**Issue by mlevin77** [jensb/iphoto2xmp#17]
Once I actually get it to work, what's next - how do I bring the content into DigiKam?  It's working a little bit for me  (creating some files/directories, before it quits with an error); looking forward to the day it finishes the run, what do I do with the resulting .sql files and the directory - how to import to DigiKam?

**Comment by jensb** [comment]
The output directory just needs to be added to Digikam as a collection.
Or copied into Digikam's existing collections. Preferably while Digikam is not running.
The SQL files that the script creates are only relevant if you have grouped photos (which I only use to combine original and edited versions of images) or you have comments in Events (which only existed as a feature until iPhoto'09, I think).

Note: if you delete these files and reimport them, you need to do some Digikam database maintenance (menu option) or re-read the metadata from the files (also a menu option), otherwise Digikam will re-use the old metadata from these files.
