### ISSUE TITLE
exiftool

### ISSUE THREAD

**Issue by erkcan** [jensb/iphoto2xmp#2]
I see that your code no longer depends on exiftool. But I guess you forgot to remove the exiftool checking part at the beginning of your code.

By the way, thanks a lot for this tool. I am looking for an open-source alternative to iPhoto as I don't want to be left to the whims of Apple's undocumented features. Thanks to your code, I will have a chance to seriously consider moving to digiKam.

**Comment by jensb** [comment]
Thanks and you're welcome :-)
Yes, the reference to exiftool can indeed be removed completely. With the last few commits, even grouping and album properties (comments, thumbnails etc) are exported from iPhoto. However, the export is Digikam specific since I need to modify Digikam's SQL database to transfer this information.
