### ISSUE TITLE
Across devices, directory name, and rerun overwrite questions

### ISSUE THREAD

**Issue by zzaappedd** [jensb/iphoto2xmp#8]
At first try I failed because I was pointing to directories on different devices. Ran it with i/o in same directory and it worked (noob here, so might be my fault, but it can help others).
Made a mistake on escaping the space of the iphoto directory (noob alert) 

More importantly and the reason for me writing this is that there was an error that stopped the process 75% through my 80gb library. I would like to rerun the script but don't know if it appends or overwrites previous work. Not versed on code well enough to check on my own. Thanks.

and I forgot, too bad this awesome effort of yours hasn't made it to the top of google searches on the subject. A lot of painful proccesses on countless blogs involving exiftool and just plain giving up on metadata preservation; thank you for sharing this huge effort.

**Comment by jensb** [comment]
Please quote the error message and the last lines before it while running like this:

```
 DEBUG=1 ruby iphoto2xmp.rb ...
```

The script will refuse to run twice with the same output directory because it can't guarantee that the iPhoto databse IDs have not changed in the meantime, so incremental partial output is not supported (right now). 
If you have a large database, please run it with "time" for me so I can get an idea how long the script takes.

**Comment by zzaappedd** [comment]
sorry, lots of time have passed since then and I must apologize for not following up. I ended up using Mylio to transfer out of iphoto, but I'm back here because Mylio failed to pickup some jp2 files out of iphoto. Luckily I found out and rescued 1100 photos before I erased forever my iphoto library. What an odyssey.

**Comment by mlevin77** [comment]
Can you tell me more, how do you use Mylio to get data out of iPhoto?
